<?php

namespace App\Actions;

use App\Models\AffiliateType;
use App\Models\Cluster;
use App\Models\Event;
use App\Models\EventCompany;
use App\Models\EventRecurring;
use App\Models\EventSlot;
use App\Models\EventTag;
use App\Models\Program;
use App\Models\TagsEvent;
use Carbon\Carbon;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Fieldset;
use Filament\Forms\Components\Grid;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\ToggleButtons;
use Filament\Forms\Get;
use Filament\Notifications\Notification;
use Ysfkaya\FilamentPhoneInput\Forms\PhoneInput;

final class EventUpdateAction
{
    public function execute($data,$record)
    {
        $data['updated_by'] = auth()->id();
        $data['updated_at'] = now();
        $data['start_date'] = $data['date'].' '.$data['start_time'].':00';
        $data['end_date'] = $data['date'].' '.$data['end_time'].':00';

        $new_start_date = Carbon::parse($record->start_date)->diffInSeconds($data['start_date'], false);
        $new_end_date = Carbon::parse($record->end_date)->diffInSeconds($data['end_date'], false);

        $tag_arr = array();

        if(isset($data['tags']) && $data['tags']){

            $record->tags()->detach(); // Delete existing tags
            $tag_arr = $data['tags'];
        }
        unset($data['tags']);

        if($record->event_recurring_id){ // Recurring Events

            // Get all future events
            $records = Event::where('event_recurring_id',$record->event_recurring_id)->where('start_date', '>', Carbon::parse($record->start_date)->startOfDay())->get();

        }else { // One-time event
            $records = collect([$record]); // Model to Collection
        }

        foreach ($records as $event) {

            $data['start_date'] = Carbon::parse($event->start_date)->addSeconds($new_start_date);
            $data['end_date'] = Carbon::parse($event->end_date)->addSeconds($new_end_date);
            $event->update($data);

            // Insert Slots
            (new SaveEventSlotsAction())->execute($event,$data,true);

            // Insert Event companies
            (new SaveEventCompaniesAction())->execute($event,$data,true);

            // Insert Event Tags
            (new SaveEventTagsAction())->execute($event,$tag_arr,true);

        }

        return $record; // TODO: Change the autogenerated stub
    }

}
