<?php

namespace App\Actions;

use App\Models\AffiliateType;
use App\Models\Cluster;
use App\Models\Event;
use App\Models\EventCompany;
use App\Models\EventRecurring;
use App\Models\EventSlot;
use App\Models\EventTag;
use App\Models\Program;
use App\Models\TagsEvent;
use Carbon\Carbon;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Fieldset;
use Filament\Forms\Components\Grid;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\ToggleButtons;
use Filament\Forms\Get;
use Filament\Notifications\Notification;
use Ysfkaya\FilamentPhoneInput\Forms\PhoneInput;

final class EventUpdateAction
{
    public function execute($data,$record)
    {
        $data['updated_by'] = auth()->id();
        $data['updated_at'] = now();
        $data['start_date'] = $data['date'].' '.$data['start_time'].':00';
        $data['end_date'] = $data['date'].' '.$data['end_time'].':00';

        $new_start_date = Carbon::parse($record->start_date)->diffInSeconds($data['start_date'], false);
        $new_end_date = Carbon::parse($record->end_date)->diffInSeconds($data['end_date'], false);

        $tag_arr = array();

        if(isset($data['tags']) && $data['tags']){

            $record->tags()->detach(); // Delete existing tags
            $tag_arr = $data['tags'];
        }
        unset($data['tags']);

        $facilitator_arr = array();
        if(isset($data['facilitators']) && $data['facilitators']){
            $facilitator_arr = $data['facilitators'];
        }
        unset($data['facilitators']);

        // Check if this should become a recurring event
        if(isset($data['recurrence_type_id']) && $data['recurrence_type_id'] == 2 && !$record->event_recurring_id){
            // Converting one-time event to recurring event
            $this->convertToRecurringEvent($data, $record, $tag_arr, $facilitator_arr);

            Notification::make()
                ->title('Event successfully converted to recurring.')
                ->success()
                ->send();

            return $record;
        }

        // Check if recurring event should become one-time event
        if((!isset($data['recurrence_type_id']) || $data['recurrence_type_id'] != 2) && $record->event_recurring_id){
            // Converting recurring event to one-time event
            $this->convertToOneTimeEvent($data, $record, $tag_arr, $facilitator_arr);

            Notification::make()
                ->title('Event successfully converted to one-time event.')
                ->success()
                ->send();

            return $record;
        }

        if($record->event_recurring_id){ // Recurring Events

            // Sync facilitators on the current record itself (not included in future events query)
            $record->facilitators()->sync($facilitator_arr);

            // Get all future events
            $records = Event::where('event_recurring_id',$record->event_recurring_id)->where('start_date', '>', Carbon::parse($record->start_date)->startOfDay())->get();

        }else { // One-time event
            $records = collect([$record]); // Model to Collection
        }

        foreach ($records as $event) {

            $data['start_date'] = Carbon::parse($event->start_date)->addSeconds($new_start_date);
            $data['end_date'] = Carbon::parse($event->end_date)->addSeconds($new_end_date);
            $event->update($data);

            // Insert Slots
            (new SaveEventSlotsAction())->execute($event,$data,true);

            // Insert Event companies
            (new SaveEventCompaniesAction())->execute($event,$data,true);

            // Insert Event Tags
            (new SaveEventTagsAction())->execute($event,$tag_arr,true);

            // Sync Facilitators
            $event->facilitators()->sync($facilitator_arr);

        }

        // Update media for the record
        $this->updateEventMedia($record, $data);

        Notification::make()
            ->title('Event updated successfully.')
            ->success()
            ->send();

        return $record; // TODO: Change the autogenerated stub
    }

    public function remove_folder_number($media_file)
    {
        // Find the position of the first '/'
        $pos = strpos($media_file, '/');

        // Extract the substring from the position of the first '/' to the end
        $result = substr($media_file, $pos + 1);

        return $result;
    }

    private function convertToRecurringEvent($data, $record, $tag_arr, $facilitator_arr = [])
    {
        // Recurring Function (same as in EventCreateAction)
        $recurrences = [
            'daily'     => [
                'function'  => 'addDay'
            ],
            'weekly'    => [
                'function'  => 'addWeek'
            ],
            'monthly'    => [
                'function'  => 'addMonth'
            ],
            'yearly'    => [
                'function'  => 'addYear'
            ]
        ];

        $data['repeat_until'] = Carbon::parse($data['repeat_until'])->endOfDay();

        $start = Carbon::parse($data['start_date']); // Start date
        $end = Carbon::parse($data['end_date']); // End date
        $repeat_until = $data['repeat_until'];

        $recurrence = $recurrences[$data['frequency']] ?? null;

        if($recurrence){
            // Create EventRecurring record
            $recurring_data = $data;
            $recurring_data['created_by'] = auth()->id();
            $recurring_data['created_at'] = now();
            $event_recurring = EventRecurring::create($recurring_data);
            $data['event_recurring_id'] = $event_recurring->id;

            // Update the original event with recurring data
            $record->update($data);

            // Update media for the original event
            $this->updateEventMedia($record, $data);

            // Insert Slots, Companies, and Tags for original event
            (new SaveEventSlotsAction())->execute($record, $data, true);
            (new SaveEventCompaniesAction())->execute($record, $data, true);
            (new SaveEventTagsAction())->execute($record, $tag_arr, true);
            $record->facilitators()->sync($facilitator_arr);

            // Create additional recurring events
            while ($start->format('Y-m-d') < $repeat_until->format('Y-m-d'))
            {
                $event_data = $data; // Create a copy of data for each event
                $event_data['start_date'] = $start->{$recurrence['function']}()->format('Y-m-d H:i:s');
                $event_data['end_date'] = $end->{$recurrence['function']}()->format('Y-m-d H:i:s');

                // Ensure created_by is set for new events
                $event_data['created_by'] = $event_data['created_by'] ?? auth()->id();
                $event_data['created_at'] = now();

                $event = Event::create($event_data);

                // Copy media from the original event to new recurring events
                // Copy banner media
                foreach ($record->getMedia('event-banner-attachments') as $media) {
                    $event->addMedia($media->getPath())->preservingOriginal()->toMediaCollection('event-banner-attachments');
                }

                // Copy certificate background media
                foreach ($record->getMedia('certificate_background') as $media) {
                    $event->addMedia($media->getPath())->preservingOriginal()->toMediaCollection('certificate_background');
                }

                // Copy event attachments
                foreach ($record->getMedia('event-attachments') as $media) {
                    $event->addMedia($media->getPath())->preservingOriginal()->toMediaCollection('event-attachments');
                }

                // Insert Slots
                (new SaveEventSlotsAction())->execute($event, $event_data, false);

                // Insert Event companies
                (new SaveEventCompaniesAction())->execute($event, $event_data, false);

                // Insert Event Tags
                (new SaveEventTagsAction())->execute($event, $tag_arr, false);

                // Sync Facilitators
                $event->facilitators()->sync($facilitator_arr);
            }
        }
    }

    private function updateEventMedia($record, $data)
    {
        // BANNER - Update media  - Start
        $existing_media_array = $record->getMedia('event-banner-attachments')->pluck('file_name')->toArray();
        $new_media_array = array();

        if (isset($data['media_banner']) && $data['media_banner']) {
            foreach ($data['media_banner'] as $media) {
                $new_media_array[] = $this->remove_folder_number($media);
            }
        }

        // Delete existing file
        foreach ($record->getMedia('event-banner-attachments') as $media) {
            if(!in_array($media->file_name, $new_media_array)){ // If not in the uploaded file
                $media->delete();
            }
        }

        if (isset($data['media_banner']) && $data['media_banner']) {
            foreach ($data['media_banner'] as $media) {
                $sourcePath = storage_path('app/public/' . $media);

                if(!in_array($this->remove_folder_number($media), $existing_media_array)){ // If not in the existing file
                    $record->addMedia($sourcePath)->toMediaCollection('event-banner-attachments');
                }
            }
        }
        // BANNER - Update media - End

        // ATTACHMENTS Update media - Start
        $existing_media_array = $record->getMedia('event-attachments')->pluck('file_name')->toArray();
        $new_media_array = array();

        if (isset($data['media']) && $data['media']) {
            foreach ($data['media'] as $media) {
                $new_media_array[] = $this->remove_folder_number($media);
            }
        }

        // Delete existing file
        foreach ($record->getMedia('event-attachments') as $media) {
            if(!in_array($media->file_name, $new_media_array)){ // If not in the uploaded file
                $media->delete();
            }
        }

        if (isset($data['media']) && $data['media']) {
            foreach ($data['media'] as $media) {
                $sourcePath = storage_path('app/public/' . $media);

                if(!in_array($this->remove_folder_number($media), $existing_media_array)){ // If not in the existing file
                    $record->addMedia($sourcePath)->toMediaCollection('event-attachments');
                }
            }
        }
        // ATTACHMENTS Update media - End

        // Certificate Update media - Start
        $existing_media_array = $record->getMedia('certificate_background')->pluck('file_name')->toArray();
        $new_media_array = array();

        if (isset($data['certificate_background']) && $data['certificate_background']) {
            foreach ($data['certificate_background'] as $media) {
                $new_media_array[] = $this->remove_folder_number($media);
            }
        }

        // Delete existing file
        foreach ($record->getMedia('certificate_background') as $media) {
            if(!in_array($media->file_name, $new_media_array)){ // If not in the uploaded file
                $media->delete();
            }
        }

        if (isset($data['certificate_background']) && $data['certificate_background']) {
            foreach ($data['certificate_background'] as $media) {
                $sourcePath = storage_path('app/public/' . $media);

                if(!in_array($this->remove_folder_number($media), $existing_media_array)){ // If not in the existing file
                    $record->addMedia($sourcePath)->toMediaCollection('certificate_background');
                }
            }
        }
        // Certificate Update media - End
    }

    private function convertToOneTimeEvent($data, $record, $tag_arr, $facilitator_arr = [])
    {
        $event_recurring_id = $record->event_recurring_id;

        // Remove recurring reference from current event
        $data['event_recurring_id'] = null;
        $data['recurrence_type_id'] = 1; // Set to one-time
        $record->update($data);

        // Update media for the record
        $this->updateEventMedia($record, $data);

        // Insert Slots, Companies, and Tags for the event
        (new SaveEventSlotsAction())->execute($record, $data, true);
        (new SaveEventCompaniesAction())->execute($record, $data, true);
        (new SaveEventTagsAction())->execute($record, $tag_arr, true);
        $record->facilitators()->sync($facilitator_arr);

        // Delete all future events in this recurring series
        Event::where('event_recurring_id', $event_recurring_id)
            ->where('start_date', '>', Carbon::parse($record->start_date)->startOfDay())
            ->delete();

        // Delete the EventRecurring record if no other events reference it
        $remaining_events = Event::where('event_recurring_id', $event_recurring_id)->count();
        if($remaining_events <= 1) {
            EventRecurring::where('id', $event_recurring_id)->delete();
        }
    }

}
