<?php

namespace App\Filament\Resources\VolunteerResource\Pages;

use App\Filament\Resources\VolunteerResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateVolunteer extends CreateRecord
{
    protected static ?string $title = 'Add Volunteer';
    protected static string $resource = VolunteerResource::class;

    protected function handleRecordCreation(array $data): Model
    {
        $data['volunteer'] = 1;
        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
    }
}
