<?php

namespace App\Filament\Resources\EventResource\Pages;

use App\Actions\EventFillFormAction;
use App\Filament\Resources\EventResource;
use Filament\Actions\EditAction;
use Filament\Resources\Pages\ViewRecord;
use Illuminate\Database\Eloquent\Model;

class ViewEvent extends ViewRecord
{
    protected static string $resource = EventResource::class;

    protected static string $view = 'filament.resources.event-resource.pages.view-event';

    protected function mutateFormDataBeforeFill(array $data): array
    {
        $data = (new EventFillFormAction())->execute($this->record,$data);

        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }

     protected function getActions(): array
     {
         return [
             EditAction::make()
         ];
     }

}
